package com.boucheriebenz.eboucherie.recherche.model;

// Generated 17 janv. 2013 16:53:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Adresse generated by hbm2java
 */
@Entity
@Table(name = "adresse", catalog = "eBoucherie")
public class Adresse implements java.io.Serializable {

	private Integer idAdresse;
	private String destinataire;
	private String apt;
	private String lieuDit;
	private String rue;
	private String commune;
	private String cpVille;
	private String pays;
	private int client;

	public Adresse() {
	}

	public Adresse(String destinataire, String rue, String cpVille, int client) {
		this.destinataire = destinataire;
		this.rue = rue;
		this.cpVille = cpVille;
		this.client = client;
	}

	public Adresse(String destinataire, String apt, String lieuDit, String rue,
			String commune, String cpVille, String pays, int client) {
		this.destinataire = destinataire;
		this.apt = apt;
		this.lieuDit = lieuDit;
		this.rue = rue;
		this.commune = commune;
		this.cpVille = cpVille;
		this.pays = pays;
		this.client = client;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_adresse", unique = true, nullable = false)
	public Integer getIdAdresse() {
		return this.idAdresse;
	}

	public void setIdAdresse(Integer idAdresse) {
		this.idAdresse = idAdresse;
	}

	@Column(name = "destinataire", nullable = false, length = 50)
	public String getDestinataire() {
		return this.destinataire;
	}

	public void setDestinataire(String destinataire) {
		this.destinataire = destinataire;
	}

	@Column(name = "apt", length = 50)
	public String getApt() {
		return this.apt;
	}

	public void setApt(String apt) {
		this.apt = apt;
	}

	@Column(name = "lieu_dit", length = 50)
	public String getLieuDit() {
		return this.lieuDit;
	}

	public void setLieuDit(String lieuDit) {
		this.lieuDit = lieuDit;
	}

	@Column(name = "rue", nullable = false, length = 225)
	public String getRue() {
		return this.rue;
	}

	public void setRue(String rue) {
		this.rue = rue;
	}

	@Column(name = "commune", length = 225)
	public String getCommune() {
		return this.commune;
	}

	public void setCommune(String commune) {
		this.commune = commune;
	}

	@Column(name = "cp_ville", nullable = false, length = 100)
	public String getCpVille() {
		return this.cpVille;
	}

	public void setCpVille(String cpVille) {
		this.cpVille = cpVille;
	}

	@Column(name = "pays", length = 225)
	public String getPays() {
		return this.pays;
	}

	public void setPays(String pays) {
		this.pays = pays;
	}

	@Column(name = "client", nullable = false)
	public int getClient() {
		return this.client;
	}

	public void setClient(int client) {
		this.client = client;
	}

}
