package com.boucheriebenz.eboucherie.recherche.model;

// Generated 17 janv. 2013 16:53:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Animal generated by hbm2java
 */
@Entity
@Table(name = "animal", catalog = "eBoucherie")
public class Animal implements java.io.Serializable {

	private Integer idAnimal;
	private Integer age;
	private Double poids;
	private String sexe;
	private String type;
	private String race;
	private int numTrac;
	private double prixMin;
	private Double prixMax;

	public Animal() {
	}

	public Animal(String type, String race, int numTrac, double prixMin) {
		this.type = type;
		this.race = race;
		this.numTrac = numTrac;
		this.prixMin = prixMin;
	}

	public Animal(Integer age, Double poids, String sexe, String type,
			String race, int numTrac, double prixMin, Double prixMax) {
		this.age = age;
		this.poids = poids;
		this.sexe = sexe;
		this.type = type;
		this.race = race;
		this.numTrac = numTrac;
		this.prixMin = prixMin;
		this.prixMax = prixMax;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_animal", unique = true, nullable = false)
	public Integer getIdAnimal() {
		return this.idAnimal;
	}

	public void setIdAnimal(Integer idAnimal) {
		this.idAnimal = idAnimal;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "poids", precision = 22, scale = 0)
	public Double getPoids() {
		return this.poids;
	}

	public void setPoids(Double poids) {
		this.poids = poids;
	}

	@Column(name = "sexe", length = 50)
	public String getSexe() {
		return this.sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

	@Column(name = "type", nullable = false, length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "race", nullable = false, length = 50)
	public String getRace() {
		return this.race;
	}

	public void setRace(String race) {
		this.race = race;
	}

	@Column(name = "num_trac", nullable = false)
	public int getNumTrac() {
		return this.numTrac;
	}

	public void setNumTrac(int numTrac) {
		this.numTrac = numTrac;
	}

	@Column(name = "prix_min", nullable = false, precision = 22, scale = 0)
	public double getPrixMin() {
		return this.prixMin;
	}

	public void setPrixMin(double prixMin) {
		this.prixMin = prixMin;
	}

	@Column(name = "prix_max", precision = 22, scale = 0)
	public Double getPrixMax() {
		return this.prixMax;
	}

	public void setPrixMax(Double prixMax) {
		this.prixMax = prixMax;
	}

}
