package com.boucheriebenz.eboucherie.recherche.model;

// Generated 17 janv. 2013 16:53:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AnimalPhotoId generated by hbm2java
 */
@Embeddable
public class AnimalPhotoId implements java.io.Serializable {

	private int animal;
	private int photo;

	public AnimalPhotoId() {
	}

	public AnimalPhotoId(int animal, int photo) {
		this.animal = animal;
		this.photo = photo;
	}

	@Column(name = "animal", nullable = false)
	public int getAnimal() {
		return this.animal;
	}

	public void setAnimal(int animal) {
		this.animal = animal;
	}

	@Column(name = "photo", nullable = false)
	public int getPhoto() {
		return this.photo;
	}

	public void setPhoto(int photo) {
		this.photo = photo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnimalPhotoId))
			return false;
		AnimalPhotoId castOther = (AnimalPhotoId) other;

		return (this.getAnimal() == castOther.getAnimal())
				&& (this.getPhoto() == castOther.getPhoto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAnimal();
		result = 37 * result + this.getPhoto();
		return result;
	}

}
