package com.boucheriebenz.eboucherie.recherche.model;

// Generated 17 janv. 2013 16:53:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ArticlePreparation generated by hbm2java
 */
@Entity
@Table(name = "article_preparation", catalog = "eBoucherie")
public class ArticlePreparation implements java.io.Serializable {

	private ArticlePreparationId id;

	public ArticlePreparation() {
	}

	public ArticlePreparation(ArticlePreparationId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "article", column = @Column(name = "article", nullable = false)),
			@AttributeOverride(name = "preparation", column = @Column(name = "preparation", nullable = false)) })
	public ArticlePreparationId getId() {
		return this.id;
	}

	public void setId(ArticlePreparationId id) {
		this.id = id;
	}

}
