package com.boucheriebenz.eboucherie.recherche.model;

// Generated 17 janv. 2013 16:53:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ArticlePhoto generated by hbm2java
 */
@Entity
@Table(name = "article_photo", catalog = "eBoucherie")
public class ArticlePhoto implements java.io.Serializable {

	private ArticlePhotoId id;

	public ArticlePhoto() {
	}

	public ArticlePhoto(ArticlePhotoId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "article", column = @Column(name = "article", nullable = false)),
			@AttributeOverride(name = "photo", column = @Column(name = "photo", nullable = false)) })
	public ArticlePhotoId getId() {
		return this.id;
	}

	public void setId(ArticlePhotoId id) {
		this.id = id;
	}

}
