package com.boucheriebenz.eboucherie.recherche.model;

// Generated 17 janv. 2013 16:53:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Article generated by hbm2java
 */
@Entity
@Table(name = "article", catalog = "eBoucherie")
public class Article implements java.io.Serializable {

	private Integer idArticle;
	private String libelle;
	private String type;
	private String race;
	private int tarif;

	public Article() {
	}

	public Article(String libelle, String type, String race, int tarif) {
		this.libelle = libelle;
		this.type = type;
		this.race = race;
		this.tarif = tarif;
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_article", unique = true, nullable = false)
	public Integer getIdArticle() {
		return this.idArticle;
	}

	public void setIdArticle(Integer idArticle) {
		this.idArticle = idArticle;
	}

	@Column(name = "libelle", nullable = false, length = 50)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "type", nullable = false, length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "race", nullable = false, length = 50)
	public String getRace() {
		return this.race;
	}

	public void setRace(String race) {
		this.race = race;
	}

	@Column(name = "tarif", nullable = false)
	public int getTarif() {
		return this.tarif;
	}

	public void setTarif(int tarif) {
		this.tarif = tarif;
	}

}
