package com.boucheriebenz.eboucherie.recherche.model;

// Generated 17 janv. 2013 16:53:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArticlePreparationId generated by hbm2java
 */
@Embeddable
public class ArticlePreparationId implements java.io.Serializable {

	private int article;
	private int preparation;

	public ArticlePreparationId() {
	}

	public ArticlePreparationId(int article, int preparation) {
		this.article = article;
		this.preparation = preparation;
	}

	@Column(name = "article", nullable = false)
	public int getArticle() {
		return this.article;
	}

	public void setArticle(int article) {
		this.article = article;
	}

	@Column(name = "preparation", nullable = false)
	public int getPreparation() {
		return this.preparation;
	}

	public void setPreparation(int preparation) {
		this.preparation = preparation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArticlePreparationId))
			return false;
		ArticlePreparationId castOther = (ArticlePreparationId) other;

		return (this.getArticle() == castOther.getArticle())
				&& (this.getPreparation() == castOther.getPreparation());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getArticle();
		result = 37 * result + this.getPreparation();
		return result;
	}

}
