package com.boucheriebenz.eboucherie.recherche.model;

// Generated 17 janv. 2013 16:53:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Authentification generated by hbm2java
 */
@Entity
@Table(name = "authentification", catalog = "eBoucherie")
public class Authentification implements java.io.Serializable {

	private Integer idAuthen;
	private String login;
	private String password;
	private String role;
	private String dernierecoAdressIp;
	private Date dernierecoDate;
	private int client;

	public Authentification() {
	}

	public Authentification(String login, String password, String role,
			int client) {
		this.login = login;
		this.password = password;
		this.role = role;
		this.client = client;
	}

	public Authentification(String login, String password, String role,
			String dernierecoAdressIp, Date dernierecoDate, int client) {
		this.login = login;
		this.password = password;
		this.role = role;
		this.dernierecoAdressIp = dernierecoAdressIp;
		this.dernierecoDate = dernierecoDate;
		this.client = client;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_authen", unique = true, nullable = false)
	public Integer getIdAuthen() {
		return this.idAuthen;
	}

	public void setIdAuthen(Integer idAuthen) {
		this.idAuthen = idAuthen;
	}

	@Column(name = "login", nullable = false, length = 65535)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", nullable = false, length = 15)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "role", nullable = false, length = 50)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "derniereco_adressIP", length = 50)
	public String getDernierecoAdressIp() {
		return this.dernierecoAdressIp;
	}

	public void setDernierecoAdressIp(String dernierecoAdressIp) {
		this.dernierecoAdressIp = dernierecoAdressIp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "derniereco_date", length = 0)
	public Date getDernierecoDate() {
		return this.dernierecoDate;
	}

	public void setDernierecoDate(Date dernierecoDate) {
		this.dernierecoDate = dernierecoDate;
	}

	@Column(name = "client", nullable = false)
	public int getClient() {
		return this.client;
	}

	public void setClient(int client) {
		this.client = client;
	}

}
