package com.boucheriebenz.eboucherie.recherche.model;

// Generated 17 janv. 2013 16:53:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "eBoucherie")
public class Client implements java.io.Serializable {

	private int idClient;
	private String nom;
	private String prenom;
	private int groupeTarif;

	public Client() {
	}

	public Client(String nom, String prenom, int groupeTarif) {
		this.nom = nom;
		this.prenom = prenom;
		this.groupeTarif = groupeTarif;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_client", unique = true, nullable = false)
	public int getIdClient() {
		return this.idClient;
	}

	public void setIdClient(int idClient) {
		this.idClient = idClient;
	}

	@Column(name = "nom", nullable = false, length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false, length = 100)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "groupe_tarif", nullable = false)
	public int getGroupeTarif() {
		return this.groupeTarif;
	}

	public void setGroupeTarif(int groupeTarif) {
		this.groupeTarif = groupeTarif;
	}

}
