package com.boucheriebenz.eboucherie.recherche.model;

// Generated 17 janv. 2013 16:53:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CommandeLigne generated by hbm2java
 */
@Entity
@Table(name = "commande_ligne", catalog = "eBoucherie")
public class CommandeLigne implements java.io.Serializable {

	private Integer idLigne;
	private int article;
	private int quantite;
	private double total;
	private int commande;

	public CommandeLigne() {
	}

	public CommandeLigne(int article, int quantite, double total, int commande) {
		this.article = article;
		this.quantite = quantite;
		this.total = total;
		this.commande = commande;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_ligne", unique = true, nullable = false)
	public Integer getIdLigne() {
		return this.idLigne;
	}

	public void setIdLigne(Integer idLigne) {
		this.idLigne = idLigne;
	}

	@Column(name = "article", nullable = false)
	public int getArticle() {
		return this.article;
	}

	public void setArticle(int article) {
		this.article = article;
	}

	@Column(name = "quantite", nullable = false)
	public int getQuantite() {
		return this.quantite;
	}

	public void setQuantite(int quantite) {
		this.quantite = quantite;
	}

	@Column(name = "total", nullable = false, precision = 22, scale = 0)
	public double getTotal() {
		return this.total;
	}

	public void setTotal(double total) {
		this.total = total;
	}

	@Column(name = "commande", nullable = false)
	public int getCommande() {
		return this.commande;
	}

	public void setCommande(int commande) {
		this.commande = commande;
	}

}
