package com.boucheriebenz.eboucherie.recherche.model;

// Generated 17 janv. 2013 16:53:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Log generated by hbm2java
 */
@Entity
@Table(name = "log", catalog = "eBoucherie")
public class Log implements java.io.Serializable {

	private Integer idLog;
	private String adresseIp;
	private Date date;
	private int authen;

	public Log() {
	}

	public Log(String adresseIp, Date date, int authen) {
		this.adresseIp = adresseIp;
		this.date = date;
		this.authen = authen;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_log", unique = true, nullable = false)
	public Integer getIdLog() {
		return this.idLog;
	}

	public void setIdLog(Integer idLog) {
		this.idLog = idLog;
	}

	@Column(name = "adresseIP", nullable = false, length = 50)
	public String getAdresseIp() {
		return this.adresseIp;
	}

	public void setAdresseIp(String adresseIp) {
		this.adresseIp = adresseIp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 0)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "authen", nullable = false)
	public int getAuthen() {
		return this.authen;
	}

	public void setAuthen(int authen) {
		this.authen = authen;
	}

}
