package com.boucheriebenz.eboucherie.recherche.model;

// Generated 17 janv. 2013 16:53:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Photo generated by hbm2java
 */
@Entity
@Table(name = "photo", catalog = "eBoucherie")
public class Photo implements java.io.Serializable {

	private Integer idPhoto;
	private String libelle;
	private String lien;

	public Photo() {
	}

	public Photo(String lien) {
		this.lien = lien;
	}

	public Photo(String libelle, String lien) {
		this.libelle = libelle;
		this.lien = lien;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_photo", unique = true, nullable = false)
	public Integer getIdPhoto() {
		return this.idPhoto;
	}

	public void setIdPhoto(Integer idPhoto) {
		this.idPhoto = idPhoto;
	}

	@Column(name = "libelle", length = 50)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "lien", nullable = false, length = 50)
	public String getLien() {
		return this.lien;
	}

	public void setLien(String lien) {
		this.lien = lien;
	}

}
