package com.boucheriebenz.eboucherie.recherche.model;

// Generated 17 janv. 2013 16:53:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Preparation generated by hbm2java
 */
@Entity
@Table(name = "preparation", catalog = "eBoucherie")
public class Preparation implements java.io.Serializable {

	private Integer idPreparation;
	private String libelle;

	public Preparation() {
	}

	public Preparation(String libelle) {
		this.libelle = libelle;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_preparation", unique = true, nullable = false)
	public Integer getIdPreparation() {
		return this.idPreparation;
	}

	public void setIdPreparation(Integer idPreparation) {
		this.idPreparation = idPreparation;
	}

	@Column(name = "libelle", nullable = false, length = 50)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

}
