package com.boucheriebenz.eboucherie.recherche.model;

// Generated 17 janv. 2013 16:53:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PromotionPhoto generated by hbm2java
 */
@Entity
@Table(name = "promotion_photo", catalog = "eBoucherie")
public class PromotionPhoto implements java.io.Serializable {

	private PromotionPhotoId id;

	public PromotionPhoto() {
	}

	public PromotionPhoto(PromotionPhotoId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "promotion", column = @Column(name = "promotion", nullable = false)),
			@AttributeOverride(name = "photo", column = @Column(name = "photo", nullable = false)) })
	public PromotionPhotoId getId() {
		return this.id;
	}

	public void setId(PromotionPhotoId id) {
		this.id = id;
	}

}
