package com.boucheriebenz.eboucherie.recherche.model;

// Generated 17 janv. 2013 16:53:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Promotion generated by hbm2java
 */
@Entity
@Table(name = "promotion", catalog = "eBoucherie")
public class Promotion implements java.io.Serializable {

	private Integer idPromotion;
	private String titre;
	private int article;
	private String texte;

	public Promotion() {
	}

	public Promotion(String titre, int article) {
		this.titre = titre;
		this.article = article;
	}

	public Promotion(String titre, int article, String texte) {
		this.titre = titre;
		this.article = article;
		this.texte = texte;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_promotion", unique = true, nullable = false)
	public Integer getIdPromotion() {
		return this.idPromotion;
	}

	public void setIdPromotion(Integer idPromotion) {
		this.idPromotion = idPromotion;
	}

	@Column(name = "titre", nullable = false, length = 50)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Column(name = "article", nullable = false)
	public int getArticle() {
		return this.article;
	}

	public void setArticle(int article) {
		this.article = article;
	}

	@Column(name = "texte", length = 65535)
	public String getTexte() {
		return this.texte;
	}

	public void setTexte(String texte) {
		this.texte = texte;
	}

}
