package com.boucheriebenz.eboucherie.recherche.model;

// Generated 17 janv. 2013 16:53:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Recette generated by hbm2java
 */
@Entity
@Table(name = "recette", catalog = "eBoucherie")
public class Recette implements java.io.Serializable {

	private Integer idRecette;
	private String libelle;
	private Date duree;
	private Integer difficulte;
	private String ingredients;
	private String etapes;
	private int article;

	public Recette() {
	}

	public Recette(String libelle, String ingredients, String etapes,
			int article) {
		this.libelle = libelle;
		this.ingredients = ingredients;
		this.etapes = etapes;
		this.article = article;
	}

	public Recette(String libelle, Date duree, Integer difficulte,
			String ingredients, String etapes, int article) {
		this.libelle = libelle;
		this.duree = duree;
		this.difficulte = difficulte;
		this.ingredients = ingredients;
		this.etapes = etapes;
		this.article = article;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_recette", unique = true, nullable = false)
	public Integer getIdRecette() {
		return this.idRecette;
	}

	public void setIdRecette(Integer idRecette) {
		this.idRecette = idRecette;
	}

	@Column(name = "libelle", nullable = false, length = 50)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "duree", length = 0)
	public Date getDuree() {
		return this.duree;
	}

	public void setDuree(Date duree) {
		this.duree = duree;
	}

	@Column(name = "difficulte")
	public Integer getDifficulte() {
		return this.difficulte;
	}

	public void setDifficulte(Integer difficulte) {
		this.difficulte = difficulte;
	}

	@Column(name = "ingredients", nullable = false, length = 65535)
	public String getIngredients() {
		return this.ingredients;
	}

	public void setIngredients(String ingredients) {
		this.ingredients = ingredients;
	}

	@Column(name = "etapes", nullable = false)
	public String getEtapes() {
		return this.etapes;
	}

	public void setEtapes(String etapes) {
		this.etapes = etapes;
	}

	@Column(name = "article", nullable = false)
	public int getArticle() {
		return this.article;
	}

	public void setArticle(int article) {
		this.article = article;
	}

}
