package com.boucheriebenz.eboucherie.recherche.model;

// Generated 17 janv. 2013 16:53:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RecettePhotoId generated by hbm2java
 */
@Embeddable
public class RecettePhotoId implements java.io.Serializable {

	private int recette;
	private int photo;

	public RecettePhotoId() {
	}

	public RecettePhotoId(int recette, int photo) {
		this.recette = recette;
		this.photo = photo;
	}

	@Column(name = "recette", nullable = false)
	public int getRecette() {
		return this.recette;
	}

	public void setRecette(int recette) {
		this.recette = recette;
	}

	@Column(name = "photo", nullable = false)
	public int getPhoto() {
		return this.photo;
	}

	public void setPhoto(int photo) {
		this.photo = photo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RecettePhotoId))
			return false;
		RecettePhotoId castOther = (RecettePhotoId) other;

		return (this.getRecette() == castOther.getRecette())
				&& (this.getPhoto() == castOther.getPhoto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRecette();
		result = 37 * result + this.getPhoto();
		return result;
	}

}
