package com.boucheriebenz.eboucherie.recherche.model;

// Generated 17 janv. 2013 16:53:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tarif generated by hbm2java
 */
@Entity
@Table(name = "tarif", catalog = "eBoucherie")
public class Tarif implements java.io.Serializable {

	private Integer idTarif;
	private double tarif1;
	private double tarif2;
	private double tarif3;
	private double tarif4;

	public Tarif() {
	}

	public Tarif(double tarif1, double tarif2, double tarif3, double tarif4) {
		this.tarif1 = tarif1;
		this.tarif2 = tarif2;
		this.tarif3 = tarif3;
		this.tarif4 = tarif4;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_tarif", unique = true, nullable = false)
	public Integer getIdTarif() {
		return this.idTarif;
	}

	public void setIdTarif(Integer idTarif) {
		this.idTarif = idTarif;
	}

	@Column(name = "tarif1", nullable = false, precision = 22, scale = 0)
	public double getTarif1() {
		return this.tarif1;
	}

	public void setTarif1(double tarif1) {
		this.tarif1 = tarif1;
	}

	@Column(name = "tarif2", nullable = false, precision = 22, scale = 0)
	public double getTarif2() {
		return this.tarif2;
	}

	public void setTarif2(double tarif2) {
		this.tarif2 = tarif2;
	}

	@Column(name = "tarif3", nullable = false, precision = 22, scale = 0)
	public double getTarif3() {
		return this.tarif3;
	}

	public void setTarif3(double tarif3) {
		this.tarif3 = tarif3;
	}

	@Column(name = "tarif4", nullable = false, precision = 22, scale = 0)
	public double getTarif4() {
		return this.tarif4;
	}

	public void setTarif4(double tarif4) {
		this.tarif4 = tarif4;
	}

}
